<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IbrahimPortfolio.DataAccess\IbrahimPortfolio.DataAccess.csproj" />
    <ProjectReference Include="..\IbrahimPortfolio.Entity\IbrahimPortfolio.Entity.csproj" />
    <ProjectReference Include="..\IbrahimPortfolio.Dto\IbrahimPortfolio.Dto.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
